### ISSUE TITLE
>1 item next basket prediction

### ISSUE THREAD

**Issue by davejm** [khesui/FPMC#1]
How might one go about changing this to predict next baskets of multiple items?

**Comment by khesui** [comment]
I do not provide friendly API for prediction. But it's not difficult to solve your problem.
Please refer to the code below
```
scores = self.compute_x_batch(u, b_tm1) 
if i == scores.argmax():
    correct_count += 1
```
The basic idea of "prediction" in FPMC (or BPR) is to select items with high scores. That is, the prediction is a rank list. You can get the list by sorting indices using values as keys.
The size of a next basket depends on you.
