### ISSUE TITLE
Baskets with multiple items

### ISSUE THREAD

**Issue by kjacks21** [khesui/FPMC#3]
If I have baskets with multiple items, what is the best way to represent this for input? For example, Figure 1 from the FPMC paper, I'd like to input User 1 (below).

![image](https://user-images.githubusercontent.com/11047068/48211515-a0842c80-e347-11e8-8400-2780c5118aed.png)

Would that input look like:

```
1 a b a
1 a b b
1 a c a
1 a c b
1 b b a
1 b b b
...etc
```
In other words, every combination of the transition items in the baskets.

**Comment by khesui** [comment]
The input would be every pairs of all items in `B_{t-1}` and an item in `B_{t}`
Take `B_{t-3}` and `B_{t-2}` for example, we should generate 2 lines of data:
1 a b c b
1 a b c c

**Comment by kjacks21** [comment]
This makes sense. Thank you for the quick reply!
